development:
  adapter: postgresql
  database: roomballot_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: roomballot_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: roomballot_production
  pool: 5
  timeout: 5000
